### PR TITLE
Fix NAND cart dumping

### LINKED ISSUE #96: Can't dump NAND save carts
GodMode9i will not read large cards such as WarioWare DIY and Pokemon White, despite the DSi Menu displaying the card's banner with no issues.

### PR DESCRIPTION
**Pull request by Epicpkmn11**
Completely untested at the moment, I don't have a NAND cart to test with

TODO:
- [x] Fix NAND cart ROM dumping
- [x] Fix NAND cart save dumping
   - [x] Safety checks and such, I don't think all `-1` type are NAND, etc
- [x] Fix NAND cart save restoring
   - Haven't started on this yet, will do so after reading works
- Face Training ROM works but save dumping is broken, save writing is untested
- Fixes #96

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
Update: This doesn't work at all, might actually make it worse as now it just fails to init the card period where before it would dump, just bad after the first 0x200

The nandCard check is working at least, but init is failing somehow, I'll probably get a NAND card of my own so I can test better so leaving this open.

**Comment by zurgeg** [comment]
> 
> 
> Update: This doesn't work at all, might actually make it worse as now it just fails to init the card period where before it would dump, just bad after the first 0x200
> 
> The nandCard check is working at least, but init is failing somehow, I'll probably get a NAND card of my own so I can test better so leaving this open.

What games use NAND saves? I probably have one

**Comment by Epicpkmn11** [comment]
> What games use NAND saves? I probably have one

WarioWare D.I.Y., Jam with the Band, and Face Training.

I've ordered a copy of Jam with the Band that should be arriving in a couple days so I'll continue on this once I can test better with that.

**Comment by Epicpkmn11** [comment]
I've got it consistently getting the full extended header correctly on my JWTB now, everything after that and the save seems to be garbage (or maybe decrypting wrong or something?) though. I'll try figure that out soon, let me know if y'all have any ideas what's wrong.

**Comment by Epicpkmn11** [comment]
ROM dumping should be working now, though only tested with Jam with the Band (EUR).

Something is up with my mode switching I think since it doesn't want to dump the save, I'll continue on that tomorrow since it's getting late.

**Comment by Epicpkmn11** [comment]
NAND save dumping and restoring is working now!

I've only tested using Jam with the Band (E) as that's the only game I have, so please let me know if WarioWare D.I.Y. and Face Training work if anyone wants to test those. Also 大合奏!バンドブラザーズ (Japanese Jam with the Band), it's the only NAND cart without the RW section location in the header so I had to hardcode that for it, I *think* it's in the same spot as JWTB (E), but I'm not 100% sure on that.

Also just testing that I didn't break anything for normal carts, I did make a few changes that affect them, though it shouldn't cause problems I don't think.

I'll go over everything and maybe do some clean up or fixes if needed tomorrow, but it should be working now at least.

**Comment by Epicpkmn11** [comment]
It seems that Face Training is dumping the ROM correctly, however the save isn't working, I think the TWL Blowfish thing might be part of it, however removing that alone isn't enough.

If someone can confirm WarioWare D.I.Y. working (or let me know if it isn't) then I think this'll be good enough, I'll probably get a copy of Face Training so I can test that properly later unless someone can figure out what's wrong with it.

**Pull request merged**
