### PR TITLE
Add german language

### PR DESCRIPTION
**Pull request by redstonekasi**
I hope I added everything correctly, if not please tell me.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Languages should be done via our Crowdin project: https://crowdin.com/project/godmode9i

**Comment by redstonekasi** [comment]
I did add this on Crowdin but it seemed like Pk11 is adding the languages manually. Is that wrong?

**Comment by lifehackerhansol** [comment]
The Crowdin is linked to @Epicpkmn11's fork of GodMode9i and a pull request is created every once in a while to synchronize translations. It's better to let that run its course as often times manually editing creates merge conflicts.

As far as I'm concerned, Crowdin autogenerates the required translations. The C line isn't, though, but as I mentioned earlier better to let Evie do it on her own account.

**Comment by redstonekasi** [comment]
Okay

**Pull request closed without merging**
